testthat::test_that("forest style arguments reach labels and geometry", {
  d <- data.frame(study = c("A", "B", "C"), TP = c(8,12,16), FP = c(3,2,1), FN = c(2,4,3), TN = c(17,18,20))
  se <- meta::metaprop(TP, TP+FN, studlab=study, data=d, method="Inverse")
  sp <- meta::metaprop(TN, TN+FP, studlab=study, data=d, method="Inverse")
  grDevices::pdf(NULL)
  on.exit(grDevices::dev.off(), add=TRUE)
  plot_sensspec_forest_meta(se, sp, header_cex=1.1, study_cex=.9, ci_text_cex=.8,
    summary_cex=1, summary_count_cex=.95, summary_ci_cex=.85, axis_cex=.75,
    row_gap=.06, square_col="steelblue", square_max_mm=4, ci_col="navy", ci_lwd=2,
    diamond_col="darkred")
  g <- as.list(grid::grid.grab()$children)
  txt <- Filter(function(x) inherits(x,"text"), g)
  label <- function(s) Filter(function(x) identical(as.character(x$label), s), txt)[[1]]
  testthat::expect_equal(label("Study")$gp$cex, 1.1)
  testthat::expect_equal(label("A")$gp$cex, .9)
  testthat::expect_equal(as.numeric(label("A")$y)-as.numeric(label("B")$y), .06)
  testthat::expect_equal(label("Total (95% CI)")$gp$cex, 1)
  testthat::expect_equal(label("36")$gp$cex, .95)
  testthat::expect_equal(label("0.0")$gp$cex, .75)
  ci_txt <- Filter(function(x) grepl("[",as.character(x$label),fixed=TRUE), txt)
  testthat::expect_equal(unname(vapply(ci_txt,function(x) x$gp$cex,numeric(1))), c(rep(.8,6),rep(.85,2)))
  boxes <- Filter(function(x) inherits(x,"rect"),g)
  testthat::expect_true(all(vapply(boxes,function(x) x$gp$fill=="steelblue",logical(1))))
  testthat::expect_equal(max(vapply(boxes,function(x) as.numeric(x$width),numeric(1))),4)
  diamonds <- Filter(function(x) inherits(x,"polygon"),g)
  testthat::expect_true(all(vapply(diamonds,function(x) x$gp$fill=="darkred",logical(1))))
  lines <- Filter(function(x) inherits(x,"segments") && identical(x$gp$col,"navy"),g)
  testthat::expect_length(lines,12)
  testthat::expect_true(all(vapply(lines,function(x) x$gp$lwd==2,logical(1))))
  for (arg in c("header_cex","study_cex","ci_text_cex","summary_cex","summary_count_cex","summary_ci_cex","axis_cex","square_max_mm","ci_lwd"))
    testthat::expect_error(do.call(plot_sensspec_forest,c(list(data=d),setNames(list(0),arg))), arg)
  testthat::expect_error(plot_sensspec_forest(d,row_gap=.3),"row_gap")
  testthat::expect_error(plot_sensspec_forest(d,row_gap=NA_real_),"row_gap")
  for (arg in c("square_col","ci_col","diamond_col"))
    testthat::expect_error(do.call(plot_sensspec_forest,c(list(data=d),setNames(list("not-a-color"),arg))),arg)
})
